Repository zuri-training/clovar_cms, pull requests merged in 2022-07, with the labels that each got.

#53 fix: add spacing to sign-up form
  templates/account/signup.html
Labels: enhancement, frontend

#58 Remove jeremiey from contributors
  README.md
Labels: bug, enhancement, backend, frontend

#60 few fixes: 0x b1
  config/settings.py
Labels: bug

#61 Update: add django-environ in pipeFile
  Pipfile
  Pipfile.lock
Labels: backend
